function Hd = filtel
%FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
% Generated on: 09-Dec-2019 11:16:18

% Elliptic Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in GHz.
Fs = 100;  % Sampling Frequency

N     = 10;  % Order
Fpass = 2;   % Passband Frequency
Apass = 1;   % Passband Ripple (dB)
Astop = 80;  % Stopband Attenuation (dB)

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.lowpass('N,Fp,Ap,Ast', N, Fpass, Apass, Astop, Fs);
Hd = design(h, 'ellip');

% [EOF]
