function Hd = filtbp
%FILTBP Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and DSP System Toolbox 9.9.
% Generated on: 09-Dec-2019 17:17:42

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in GHz.
Fs = 100;  % Sampling Frequency

Fstop1 = 12.5;            % First Stopband Frequency
Fpass1 = 13.45;           % First Passband Frequency
Fpass2 = 17.45;           % Second Passband Frequency
Fstop2 = 18.75;           % Second Stopband Frequency
Dstop1 = 0.0001;          % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.0001;          % Second Stopband Attenuation
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
